---

# Installs the service / systemloader scripts

- include_tasks: service/upstart.yml
  when: deploy_service_type == "upstart" or
        (deploy_service_type == "default" and ansible_distribution == "CentOS" and ansible_distribution_major_version == '6')