---

- name: Install - Ensure instance directories for instance {{ deploy_instance_nr }}"
  file: path={{ item }} state=directory
  with_items:
    - "{{ deploy_basedir }}"
    - "{{ deploy_instancedir }}"
    - "{{ deploy_appdir }}"
    - "{{ deploy_logsdir }}"
    - "{{ deploy_configdir }}"

- name: Install - Check artifact already downloaded
  stat:
    path: "{{ deploy_download_file }}"
    register: deploy_artifact_downloaded

- name: Download artifact {{ deploy_artifact_url }}
  get_url:
    url: "{{ deploy_artifact_url }}"
    dest: "{{ deploy_download_file }}"
    mode: 0440
  when: deploy_download_keep == False or deploy_artifact_downloaded.stat.exists == False

- name: Extract artifact zip {{ deploy_artifact_filename }}
  unarchive:
    src: "{{ deploy_download_file }}"
    dest: "{{ deploy_appdir }}"
    remote_src: yes
