---

# General tasks to do after installation

- name: "Postinstall - Remove downloaded artifact"
  become: yes
  become_user: "{{ deploy_app_user }}"
  file: path={{ item }} state=absent
  when: deploy_setting_keep_downloads == False
  with_items:
    - "{{ deploy_download_file }}"
    - "{{ deploy_download_extract_dir }}"