---

# General tasks to do before artifact installation

- name: "Preinstall - Ensure group {{ deploy_app_group }} is present"
  become: yes
  group:
    name: "{{ deploy_app_group }}"
    state: present

- name: "Preinstall - Ensure user {{ deploy_app_user }} is present"
  become: yes
  user:
    name: "{{ deploy_app_user }}"
    group: "{{ deploy_app_group }}"
    state: present

- name: "Preinstall - Ensure base directory {{ deploy_dir_base }}"
  become: yes
  file:
    path: "{{ deploy_dir_base }}"
    state: directory
    owner: "{{ deploy_app_user }}"
    group: "{{ deploy_app_group }}"

- name: "Preinstall - Ensure directories for instance {{ deploy_instance_nr }}"
  become: yes
  become_user: "{{ deploy_app_user }}"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ deploy_app_user }}"
    group: "{{ deploy_app_group }}"
  with_items:
    - "{{ deploy_download_dir }}"
    - "{{ deploy_dir_instances }}"
    - "{{ deploy_dir_instance }}"
    - "{{ deploy_dir_logs }}"
    - "{{ deploy_dir_config }}"
    - "{{ deploy_download_extract_dir }}"